# Generated by Django 6.0.3 on 2026-07-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="L'artisanat africain à son meilleur.", max_length=200)),
                ('subtitle', models.CharField(default='À propos de nous', max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('badge_text', models.CharField(blank=True, default='100% Authentique & fait main', max_length=50)),
                ('badge_value', models.CharField(blank=True, default='100%', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About content',
                'db_table': 'about_content',
            },
        ),
    ]
