# Generated by Django 6.0.3 on 2026-07-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_featureblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], default='female', max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.CharField(help_text='Ex: 15 ans', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('achievements', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artisans',
                'ordering': ['order'],
            },
        ),
    ]
