# Generated by Django 6.0.3 on 2026-07-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partners',
                'ordering': ['order'],
            },
        ),
    ]
