# Generated by Django 6.0.3 on 2026-07-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='description',
            field=models.TextField(blank=True, help_text='Description affichée entre le sous-titre et les boutons'),
        ),
        migrations.AlterField(
            model_name='featureblock',
            name='icon',
            field=models.CharField(default='FiStar', max_length=50),
        ),
    ]
