# Generated by Django 6.0.3 on 2026-07-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_heroslide_description_alter_featureblock_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='image',
            field=models.URLField(blank=True, help_text="URL Cloudinary de l'image", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.URLField(blank=True, help_text="URL Cloudinary de l'image", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.URLField(blank=True, help_text='URL Cloudinary du logo', max_length=500, null=True),
        ),
    ]
